version: 1.2
workflows:
  - name: abra2Realigner
    subclass: WDL
    primaryDescriptorPath: /abra2.wdl
  - name: SNVJudgementFilter
    subclass: WDL
    primaryDescriptorPath: /Pipeline_variantJudgment.wdl
