version: 1.2
workflows:
  - name: abra2Realigner
    subclass: WDL
    primaryDescriptorPath: /abra2.wdl
  - name: SNVJudgementFilter
    subclass: WDL
    primaryDescriptorPath: /Pipeline_variantJudgment.wdl
  - name: WGSVariantPipeline
    subclass: WDL
    primaryDescriptorPath: /WGS_variant_pipeline_main.wdl
  - name: Svaba
    subclass: WDL
    primaryDescriptorPath: /SvABA.wdl
  - name: MultiSNVCaller
    subclass: WDL
    primaryDescriptorPath: /SNV-MultiCaller.wdl
  - name: SNVGermline
    subclass: WDL
    primaryDescriptorPath: /SNV-GermlineMulti.wdl
  - name: Oncokb
    subclass: WDL
    primaryDescriptorPath: /oncokb.wdl
