version: 1.2
workflows:
  - name: abra2Realigner
    subclass: WDL
    primaryDescriptorPath: /abra2.wdl
    testParameterFiles: 
    - /json/example_input_abra2.json
  - name: SNVJudgementFilter
    subclass: WDL
    primaryDescriptorPath: /Pipeline_variantJudgment.wdl
  - name: WGSVariantPipeline
    subclass: WDL
    primaryDescriptorPath: /WGS_variant_pipeline_main.wdl
    testParameterFiles: 
    - /json/WGS_SNV_CNV_variant_pipeline.json
  - name: Svaba
    subclass: WDL
    primaryDescriptorPath: /SvABA.wdl
    testParameterFiles: 
    - /json/svaba_example.json
  - name: MultiSNVCaller
    subclass: WDL
    primaryDescriptorPath: /SNV-MultiCaller.wdl
  - name: SNVGermline
    subclass: WDL
    primaryDescriptorPath: /SNV-GermlineMulti.wdl
    testParameterFiles: 
    - /json/SNV-Germline_inputs.json   
  - name: Oncokb
    subclass: WDL
    primaryDescriptorPath: /oncokb.wdl
    testParameterFiles: 
    - /json/oncokb_inputs.json
  - name: ClinicalReport
    subclass: WDL
    primaryDescriptorPath: /CombinedClinicalReport.wdl
  - name: Manta
    subclass: WDL
    primaryDescriptorPath: /Manta1.6.wdl
    testParameterFiles: 
    - /json/Manta1.6_inputs.json
  - name: Strelka2
    subclass: WDL
    primaryDescriptorPath: /Strelka2.wdl
    testParameterFiles: 
    - /json/Strelka2_inputs.json
  - name: QCCheck
    subclass: WDL
    primaryDescriptorPath: /run_QC_checks.wdl
    testParameterFiles: 
    - /json/run_QC_checks_inputs.json
